apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-deployment
  template:
    metadata:
      labels:
        app: counter-deployment
    spec:
      containers:
        - name: c-counter-deployment
          image: dhyogosiqueira/training-kubernates:1.0
          volumeMounts:
            - mountPath: /app/data
              name: counter-storage
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: counter-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: counter-storage
          persistentVolumeClaim:
            claimName: counter-pvc
